Issue 521 restart policy
docker/docker-bench-security pull request #522
Opened 2023-04-12 15:06 UTC by andreagalle

This fix double check for both the:
- container `MaximumRetryCount`
- service `MaxAttempts`

properties to be equal to 5.

Thus, fixing the #521 issue. The fix has been succesfully tested.

2023-04-14 08:58 UTC, konstruktoid commented
Thanks!
I'll have a look as soon as possible

2023-04-25 12:00 UTC, konstruktoid requested changes

2023-04-25 12:00 UTC, konstruktoid commented on tests/5_container_runtime.sh
> +    for s in $(docker service ls --format '{{.Name}}'); do
This requires a swarm.

```sh
$ docker service ls
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
```

2023-04-26 07:12 UTC, andreagalle reviewed
Now it should work as expected. I tried it out with: `./docker-bench-security.sh -c check_5_14`

2023-04-27 08:40 UTC, konstruktoid commented
I believe you just removed the original basic functionality :)
Test without a swarm node as well.

2023-04-27 10:01 UTC, andreagalle commented
> I believe you just removed the original basic functionality :) Test without a swarm node as well.

You mean the plain check on Docker containers or rather the one on Docker services, without a swarm node?
Could you better detail which test do you expect to be failing?

2023-04-27 10:54 UTC, konstruktoid commented
The plain check on Docker containers, and the test should fail when the 'on-failure' container restart policy is not set to '5'.

2023-06-07 17:07 UTC, andreagalle commented
Indeed it works.

I mean, starting from the following Dockerfile 

    FROM alpine:latest
    CMD sh -c "ping localhost"

I built a Docker image on it 

    docker build . -t work-image:latest

and ran a couples tests with `--restart=on-failure:4` set to `4`:

    docker run -d --name=my-work-test --restart=on-failure:4 work-image:latest
    ./docker-bench-security.sh -c check_5_14

resulting in the warning below, as  expected

    [WARN] 5.14 - Ensure that the 'on-failure' container restart policy is set to '5' (Automated)
    [WARN]       * MaximumRetryCount is not set to 5: my-work-test

and with `--restart=on-failure:5` set to `5`, with no `[WARN]` here.

2023-06-07 17:23 UTC, andreagalle commented
The only issue is that in both cases (`MaximumRetryCount` and `MaxAttempts`) the container/service parameter is not `5` the warning message is alway the same as above. Although this is a minor issue, would you like to diversify them?

2023-06-07 21:14 UTC, konstruktoid commented
So sorry, I've must have misread the code.
Works great with and without swarm mode.

2023-06-07 21:15 UTC, konstruktoid commented
> The only issue is that in both cases (`MaximumRetryCount` and `MaxAttempts`) the container/service parameter is not `5` the warning message is alway the same as above. Although this is a minor issue, would you like to diversify them?

No need to diversify unless you want to, I believe the message is understandable

2023-07-07 19:16 UTC, konstruktoid approved these changes

2023-07-07 19:16 UTC, merged